name: image_crop_example
description: Demonstrates how to use the image_crop plugin.

version: 1.0.0+1

environment:
  sdk: '^2.19.6'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  image_crop:
    path: ../

flutter:
  uses-material-design: true
