name: image_crop
description: A flutter plugin to crop image on iOS and Android. It processes image files off main thread natively. The plugin provides a Crop widget to display image cropping to a user.
version: 0.5.0
homepage: https://github.com/VolodymyrLykhonis/image_crop

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.image_crop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin